### PR TITLE
Update Vijay_Varma.markdown

### PR DESCRIPTION
**Pull request by vijayvarma392**

### CODE REVIEW

**Comment by vijayvarma392** [comment]
@duetosymmetry please merge

**Comment by duetosymmetry** [comment]
@vijayvarma392 I can't, it's @moble's repo ;)

**Comment by vijayvarma392** [comment]
Should I expect the update to have happened already?
I still see myself in the Graduate Students page: https://www.black-holes.org/about-us/people

**Comment by duetosymmetry** [comment]
This is not yet the live version of the site. We need to picks some criterion for when we should transition the current site to this jekyll site.

**Pull request merged**
